port: 8083
sql:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: postgres
  name: postgres
search:
  base_url: http://localhost:8088
  index_timeout: 3s
  search_timeout: 2s
  scheduler_interval: 30s
  scheduler_batch_size: 200
  scheduler_max_retries: 3
