apiVersion: v1
kind: ConfigMap
metadata:
  name: task-service-config
  namespace: default
data:
  config.yaml: |
    port: 8083
    sql:
      host: postgres.default.svc.cluster.local
      port: 5432
      user: postgres
      password: postgres
      name: postgres
    search:
      base_url: http://search-engine.default.svc.cluster.local:8080
      index_timeout: 3s
      search_timeout: 2s
      scheduler_interval: 30s
      scheduler_batch_size: 200
      scheduler_max_retries: 3

